name: PR Build

on:
    pull_request:
        branches: [ master ]
        paths:
            - 'Hitbloq/**'
            - '.github/workflows/**.yml'

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.x
            - name: Download SIRA References
              uses: ProjectSIRA/download-sira-stripped@1.0.0
              with:
                  manifest: ${{github.workspace}}/Hitbloq/manifest.json
                  sira-server-code: ${{ secrets.SIRA_SERVER_CODE }}
            - name: Download Mod Dependencies
              uses: Goobwabber/download-beatmods-deps@1.2
              with:
                  manifest: ${{github.workspace}}/Hitbloq/manifest.json
            - name: Download LeaderboardCore
              uses: dawidd6/action-download-artifact@v2.14.1
              with:
                github_token: ${{secrets.TOKEN}}
                workflow: master.yml
                workflow_conclusion: success
                name: LeaderboardCore
                repo: rithik-b/LeaderboardCore
                path: ${{github.workspace}}/Refs
            - name: Download PlaylistManager
              uses: dawidd6/action-download-artifact@v2.14.1
              with:
                github_token: ${{secrets.TOKEN}}
                workflow: master.yml
                workflow_conclusion: success
                name: PlaylistManager
                repo: rithik-b/PlaylistManager
                path: ${{github.workspace}}/Refs
            - name: Build
              id: Build
              run: dotnet build --configuration Release
            - name: GitStatus
              run: git status
            - name: Echo Filename
              run: echo $BUILDTEXT \($ASSEMBLYNAME\)
              env:
                  BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                  ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: ${{ steps.Build.outputs.filename }}
                  path: ${{ steps.Build.outputs.artifactpath }}